apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rpe-sweet-backend"
  description: Sweet as backend
  annotations:
    github.com/project-slug: 'timja-org/rpe-sweet-backend'
    jenkins/project-folder: 'timja-org/rpe-sweet-backend'
spec:
  type: service
  lifecycle: experimental
  owner: timja
