version: '2.1'

services:
  sweet-backend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/rpe/sweet-backend
    ports:
      - $SERVER_PORT:$SERVER_PORT
