apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rpe-sweet-backend App
name: rpe-sweet-backend
home: https://github.com/hmcts/rpe-sweet-backend
version: 0.0.1
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 3.0.2
    repository: '@hmctspublic'
